Repository okaneco/rscolorq, pull requests merged in 2021-03, with the labels that each got.

#11 Add chunks_exact[_mut] methods for accessing Matrix2d rows, `no_file` flag to binary
  src/bin/rscolorq/args.rs
  src/bin/rscolorq/main.rs
  src/color/lab.rs
  src/color/rgb.rs
  src/matrix.rs
  src/quant.rs
  src/quant/utility.rs
Labels: binary, enhancement, library

#13 Executable build workflow
  .github/workflows/rust-cd.yml
Labels: enhancement

#14 Bump rand to 0.8, prepare for 0.2 release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  src/bin/rscolorq/utils.rs
  src/color/lab.rs
  src/color/rgb.rs
  src/quant/utility.rs
Labels: breaking, update, update-deps
